import { useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { Download, FileImage, Sparkles, Loader2 } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import type { Dataset } from "@/lib/cleanlab/types";
import { composeDashboard, TEMPLATES, type TemplateId } from "@/lib/cleanlab/dashboard";
import { SpecChart } from "@/components/charts/SmartCharts";
import { confidenceLabel } from "@/lib/cleanlab/recommend";

export function DashboardView({ dataset }: { dataset: Dataset }) {
  const [template, setTemplate] = useState<TemplateId>("executive");
  const [hidden, setHidden] = useState<Set<string>>(new Set());
  const [customTitle, setCustomTitle] = useState<string | null>(null);
  const [exporting, setExporting] = useState<null | "pdf" | "png">(null);
  const boardRef = useRef<HTMLDivElement>(null);

  const spec = useMemo(() => composeDashboard(dataset, template), [dataset, template]);
  const title = customTitle ?? spec.title;
  const cards = spec.cards.filter((c) => !hidden.has(c.spec.id));

  const capture = async () => {
    const el = boardRef.current;
    if (!el) return null;
    const html2canvas = (await import("html2canvas")).default;
    return html2canvas(el, {
      backgroundColor: getComputedStyle(document.body).backgroundColor,
      scale: 2,
      logging: false,
      useCORS: true,
    });
  };

  const exportPng = async () => {
    setExporting("png");
    try {
      const canvas = await capture();
      if (!canvas) return;
      const a = document.createElement("a");
      a.href = canvas.toDataURL("image/png");
      a.download = `${title.replace(/\s+/g, "-").toLowerCase()}.png`;
      a.click();
      toast.success("Dashboard image downloaded");
    } catch {
      toast.error("We couldn't render the dashboard image. Try removing a chart and retrying.");
    } finally {
      setExporting(null);
    }
  };

  const exportPdf = async () => {
    setExporting("pdf");
    try {
      const canvas = await capture();
      if (!canvas) return;
      const { jsPDF } = await import("jspdf");
      const pdf = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
      const pw = pdf.internal.pageSize.getWidth();
      const ph = pdf.internal.pageSize.getHeight();
      const margin = 28;
      const maxW = pw - margin * 2;
      const maxH = ph - margin * 2 - 34;
      const ratio = Math.min(maxW / canvas.width, maxH / canvas.height);
      const w = canvas.width * ratio;
      const h = canvas.height * ratio;

      pdf.setFontSize(15);
      pdf.text(title, margin, margin + 4);
      pdf.setFontSize(9);
      pdf.setTextColor(120);
      pdf.text(
        `${dataset.name} · ${dataset.rows.length.toLocaleString()} rows · ${dataset.columns.length} columns · generated by Nadiifi`,
        margin,
        margin + 18,
      );
      pdf.addImage(canvas.toDataURL("image/png"), "PNG", margin, margin + 30, w, h);
      pdf.save(`${title.replace(/\s+/g, "-").toLowerCase()}.pdf`);
      toast.success("Dashboard PDF downloaded");
    } catch {
      toast.error("We couldn't build the PDF. Try the PNG export instead.");
    } finally {
      setExporting(null);
    }
  };

  return (
    <div className="space-y-4">
      <Card className="flex flex-wrap items-center gap-3 p-3 shadow-soft">
        <div className="flex flex-wrap gap-1">
          {TEMPLATES.map((t) => (
            <button
              key={t.id}
              type="button"
              title={t.description}
              onClick={() => setTemplate(t.id)}
              className={cn(
                "rounded-md px-2.5 py-1.5 text-[13px] font-medium transition-colors",
                template === t.id ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted",
              )}
            >
              {t.label}
            </button>
          ))}
        </div>
        <div className="ml-auto flex gap-2">
          <Button size="sm" variant="outline" onClick={exportPng} disabled={exporting !== null} className="gap-1.5">
            {exporting === "png" ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <FileImage className="h-3.5 w-3.5" />}
            PNG
          </Button>
          <Button size="sm" onClick={exportPdf} disabled={exporting !== null} className="gap-1.5">
            {exporting === "pdf" ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
            Export PDF
          </Button>
        </div>
      </Card>

      <div ref={boardRef} className="space-y-4 rounded-xl bg-background p-4">
        <div>
          <Input
            aria-label="Dashboard title"
            value={title}
            onChange={(e) => setCustomTitle(e.target.value)}
            className="h-auto border-none bg-transparent px-0 font-display text-2xl font-semibold tracking-[-0.02em] shadow-none focus-visible:ring-0"
          />
          <p className="text-xs text-muted-foreground">
            {spec.domain !== "General" ? `${spec.domain} dataset · ` : ""}
            {dataset.rows.length.toLocaleString()} rows · {dataset.columns.length} columns · composed from cleaned data
          </p>
        </div>

        <div
          className={cn(
            "grid gap-3",
            template === "minimal" ? "sm:grid-cols-3" : "sm:grid-cols-2 lg:grid-cols-4",
          )}
        >
          {spec.kpis.map((k) => (
            <Card key={k.id} className="p-4 shadow-soft">
              <div className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">{k.label}</div>
              <div className="mt-1 font-display text-2xl font-semibold tabular-nums">{k.value}</div>
              <div className="mt-1 line-clamp-2 text-[11px] text-muted-foreground">{k.hint}</div>
            </Card>
          ))}
        </div>

        <div className="grid gap-4 lg:grid-cols-2">
          {cards.map(({ spec: c, span }) => {
            const conf = confidenceLabel(c.confidence);
            return (
              <Card key={c.id} className={cn("p-4 shadow-soft", span === 2 && "lg:col-span-2")}>
                <div className="mb-2 flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <div className="truncate text-sm font-medium">{c.title}</div>
                    <div className="truncate text-xs text-muted-foreground">{c.subtitle}</div>
                  </div>
                  <div className="flex shrink-0 items-center gap-2">
                    <span className={cn("rounded-full px-2 py-0.5 text-[10px] font-semibold", conf.tone)}>{conf.label}</span>
                    <button
                      type="button"
                      onClick={() => setHidden((s) => new Set(s).add(c.id))}
                      className="text-[11px] text-muted-foreground underline-offset-2 hover:text-foreground hover:underline"
                    >
                      remove
                    </button>
                  </div>
                </div>
                <SpecChart spec={c} height={span === 2 ? 280 : 220} />
              </Card>
            );
          })}
        </div>

        <Card className="p-4 shadow-soft">
          <div className="mb-2 flex items-center gap-2 text-sm font-medium">
            <Sparkles className="h-4 w-4 text-primary" />
            What stands out
          </div>
          <ul className="space-y-1.5 text-sm text-muted-foreground">
            {spec.insights.map((i, idx) => (
              <li key={idx} className="flex gap-2">
                <span className="mt-[7px] h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                <span>{i}</span>
              </li>
            ))}
          </ul>
          <p className="mt-2 text-[11px] text-muted-foreground">
            Every statement is calculated from the cleaned dataset — no estimates.
          </p>
        </Card>
      </div>

      {hidden.size > 0 && (
        <Button size="sm" variant="ghost" onClick={() => setHidden(new Set())}>
          Restore {hidden.size} removed chart{hidden.size > 1 ? "s" : ""}
        </Button>
      )}
    </div>
  );
}
